running_planner/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('runs/', include('runs.urls')),
]

runs/urls.py
from django.urls import include, path
from rest_framework import routers, serializers, viewsets

from runs.models import Run

from . import views

# API registration
router = routers.DefaultRouter()
router.register(r'runs', views.RunViewSet)

app_name = 'runs'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path('new/', views.new_run, name="new"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
]

runs/models.py
from django.utils import timezone
from django.conf import settings
from django.db import models

class Run(models.Model):
    distance_miles = models.FloatField()
    start_time = models.DateTimeField(default=timezone.now)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.distance_miles} miles started at {self.start_time}'

runs/forms.py
from django import forms
from django.utils import timezone

from runs.models import Run

class NewRunForm(forms.ModelForm):
    #distance_miles = forms.FloatField(label="Distance (miles)", min_value=0.0)
    #start_time = forms.DateTimeField(label="Start Time", initial=timezone.now)
    class Meta:
        model=Run
        fields = ['distance_miles', 'start_time']

    # Override to allow linking current user on new run submission
    def save(self, commit=True, user=None):
        run = super().save(commit=False)
        if user:
            run.user = user
        if commit:
            run.save()
        return run

runs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from runs.forms import NewRunForm
from runs.models import Run

from rest_framework import viewsets

from runs.serializers import RunSerializer

class IndexView(generic.ListView):
    template_name = 'runs/index.html'

    context_object_name = 'all_runs'

    # Get all of the current user's runs
    def get_queryset(self):
        return Run.objects.filter(user_id=self.request.user.id).order_by('-start_time')

class DetailView(generic.DetailView):
    model = Run
    template_name = 'runs/detail.html'

    # Only get the current user's run
    def get_queryset(self):
        return Run.objects.filter(user_id=self.request.user.id)
    
def new_run(request):
    if request.method == "POST":
        form = NewRunForm(request.POST)

        if form.is_valid():
            form.save(user=request.user)
            return HttpResponseRedirect(reverse('runs:index'))
    else:
        form = NewRunForm()
    
    return render(request, "runs/new.html", {"form": form})

class RunViewSet(viewsets.ModelViewSet):
    queryset = Run.objects.order_by('-start_time')
    serializer_class = RunSerializer

    def get_queryset(self):
        return Run.objects.filter(user_id=self.request.user.id).order_by('-start_time')

runs/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Running Planner</title>
    </head>
    <body>
        <h1>Running Planner</h1>
        <hr/>


        {% if user.is_authenticated %}
        {% block content %}{% endblock %}
        <hr/>

        <form id="logout-form" method="post" action="{% url 'runs:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link">Logout</button>
        </form>
        {% else %}
        <li><a href="{% url 'runs:login' %}?next={{ request.path }}">Login</a></li>
        {% endif %}
    </body>
</html>

runs/templates/runs/detail.html
{% extends "base.html" %}

{% block content %}
<ul>
    <li>Run length (miles): {{ run.distance_miles }}</li>
    <li>Run started at: {{ run.start_time }}</li>
</ul>
{% endblock %}

runs/templates/runs/index.html
{% extends "base.html" %}

{% block content %}
<h1>List of all runs for {{ user }}</h1>
<ul>
    {% for run in all_runs %}
        <li>
            <a href="{% url 'runs:detail' run.id %}">{{ run }}</a>
        </li>
    {% endfor %}
    <li>
      <a href="{% url 'runs:new' %}">Add New Run</a>
    </li>
</ul>
{% endblock %}

runs/templates/runs/new.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'runs:new' %}" method="post">
    {% csrf_token %}

    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}